""" Revmoe cow_id from diseases table

Revision ID: 0a008593ab2f
Revises: ecf99fba6db6
Create Date: 2025-03-20 11:09:33.957220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a008593ab2f'
down_revision: Union[str, None] = 'ecf99fba6db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diseases', 'date_diagnosed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('date_diagnosed', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
