"""Updated Schema to keep notes for cows

Revision ID: 2103b67080a0
Revises: 303c252b117c
Create Date: 2025-03-24 14:24:15.319889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2103b67080a0'
down_revision: Union[str, None] = '303c252b117c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cows', sa.Column('tag_number', sa.String(length=255), nullable=True))
    op.add_column('cows', sa.Column('notes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cows', 'notes')
    op.drop_column('cows', 'tag_number')
    # ### end Alembic commands ###
