"""Updated Schema to match frontend

Revision ID: 303c252b117c
Revises: 0a008593ab2f
Create Date: 2025-03-24 14:16:48.650659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303c252b117c'
down_revision: Union[str, None] = '0a008593ab2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cow_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cows', sa.Column('last_milked', sa.DateTime(), nullable=True))
    op.add_column('cows', sa.Column('last_fed', sa.DateTime(), nullable=True))
    op.add_column('cows', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('cows', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('cows', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cows', 'age')
    op.drop_column('cows', 'weight')
    op.drop_column('cows', 'height')
    op.drop_column('cows', 'last_fed')
    op.drop_column('cows', 'last_milked')
    op.drop_table('cow_status')
    # ### end Alembic commands ###
