"""image_url adn status for notification

Revision ID: 31a6c6bcfbdf
Revises: d8036cefc1ca
Create Date: 2025-03-26 01:06:36.532862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a6c6bcfbdf'
down_revision: Union[str, None] = 'd8036cefc1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'image_url')
    # ### end Alembic commands ###
