""" Revmoe cow_id from diseases table

Revision ID: ecf99fba6db6
Revises: 18e90e74fb79
Create Date: 2025-03-20 11:07:07.746164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ecf99fba6db6'
down_revision: Union[str, None] = '18e90e74fb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('diseases_ibfk_1', 'diseases', type_='foreignkey')
    op.drop_column('diseases', 'cow_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('cow_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('diseases_ibfk_1', 'diseases', 'cows', ['cow_id'], ['id'])
    # ### end Alembic commands ###
